printinh the contents

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -20,17 +20,21 @@ jobs:
         run: |
           wp_content_path=$(sudo find /home/ -type d -name "wp-content" -print -quit)
           if [ -z "$wp_content_path" ]; then
-            echo "wp-content directory not found"
-            exit 1
+          echo "wp-content directory not found"
+          exit 1
           fi
+          echo "contents inside wp-content git before"
+          ls -l ./wp-content/uploads/2024/03/
           if sudo rsync -av ./wp-content/uploads/2024/03/. "$wp_content_path/uploads/2024/03/"; then
-            echo "contents inside wp-content git after"
-            ls -l $wp_content_path/uploads/2024/03/
             echo "Images copied successfully."
           else
             echo "Failed to copy images."
             exit 1
+          echo "contents inside wp-content git after"
+          ls -l $wp_content_path/uploads/2024/03/
           fi
+          echo "contents inside wp-content git after"
+          ls -l $wp_content_path/uploads/2024/03/
       # cp -r ./wp-content/uploads/   /home/runner/work/demo_project_website/demo_project_website/wp-content/uploads/
       - name: GitHub Action Deploy to WP Engine
         uses: wpengine/github-action-wpe-site-deploy@v3
