pushing dev.yml

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -23,7 +23,12 @@ jobs:
           echo "wp-content directory not found"
           exit 1
           fi
-          sudo cp -r ./wp-content/uploads/* "$wp_content_path/uploads/"
+          if sudo cp -r ./wp-content/uploads/2024/* "$wp_content_path/uploads/2024"; then
+            echo "Images copied successfully."
+          else
+            echo "Failed to copy images."
+            exit 1
+          fi
       # cp -r ./wp-content/uploads/*   /home/runner/work/demo_project_website/demo_project_website/wp-content/uploads/
       - name: GitHub Action Deploy to WP Engine
         uses: wpengine/github-action-wpe-site-deploy@v3
